### ISSUE TITLE
Date parse error when querying logs

### ISSUE THREAD

**Issue by leshik** [observeinc/observe#1]
When querying a log, no matter what expression I try I always get the same error:
```
query: invalid startTime "2023-09-28T18:58:00 07:00": parsing time "2023-09-28T18:58:00 07:00" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```
Query example: `observe query -i 'XXX Product Development.Access Logs' -q 'limit 10'`

**Comment by obs-gh-jabernet** [comment]
This should have been addressed in the latest release. There was some encoding issue that lead to certain timezones being parsed incorrectly.
